# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/metadata-syntax-for-github-actions
name: 'Cypress.io'
description: 'GitHub Action for running Cypress end-to-end tests'
author: 'Gleb Bahmutov'
inputs:
  record:
    description: 'Sends test results to Cypress Dashboard'
    required: false
    default: false
  config:
    description: 'Set configuration values. Separate multiple values with a comma. The values set here override any values set in your configuration file.'
    required: false
  config-file:
    description: 'Path to a JSON file where configuration values are set.'
    required: false
    default: cypress.json
  env:
    description: 'Sets Cypress environment variables'
    required: false
  browser:
    description: 'Name of the browser to use'
    required: false
  run:
    description: 'Command that overrides cypress run'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: 'green'
  icon: 'check-square'
