name: example-recording
on:
  push:
    branches:
      - 'master'
  pull_request:
jobs:

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Cypress v9 and lower ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

  parallel:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress tests
        # normally you would write
        # uses: cypress-io/github-action@v2
        uses: ./
        # let's give this action an ID so we can refer
        # to its output values later
        id: cypress
        # Continue the build in case of an error, as we need to set the
        # commit status in the next step, both in case of success and failure
        continue-on-error: true
        with:
          working-directory: examples/v9/recording
          record: true
          parallel: true
          group: Recording example
          tag: action
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.EXAMPLE_RECORDING_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # see "outcome" and "conclusion" of a step doc
      # https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#steps-context
      # "output" can be success, failure, cancelled, or skipped
      - name: Print Dashboard URL
        run: |
          echo Cypress finished with: ${{ steps.cypress.outcome }}
          echo See results at ${{ steps.cypress.outputs.dashboardUrl }}

  group:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress tests
        # normally you would write
        # uses: cypress-io/github-action@v2
        uses: ./
        with:
          working-directory: examples/v9/recording
          record: true
          # no parallel flag, just the group name
          group: Recording group
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.EXAMPLE_RECORDING_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Cypress v10 and higher ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

  parallel-v10:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress tests
        # normally you would write
        # uses: cypress-io/github-action@v2
        uses: ./
        # let's give this action an ID so we can refer
        # to its output values later
        id: cypress
        # Continue the build in case of an error, as we need to set the
        # commit status in the next step, both in case of success and failure
        continue-on-error: true
        with:
          working-directory: examples/v10/recording
          record: true
          parallel: true
          group: Recording example v10
          tag: action
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.EXAMPLE_RECORDING_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # see "outcome" and "conclusion" of a step doc
      # https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#steps-context
      # "output" can be success, failure, cancelled, or skipped
      - name: Print Dashboard URL
        run: |
          echo Cypress finished with: ${{ steps.cypress.outcome }}
          echo See results at ${{ steps.cypress.outputs.dashboardUrl }}

  group-v10:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress tests
        # normally you would write
        # uses: cypress-io/github-action@v2
        uses: ./
        with:
          working-directory: examples/v10/recording
          record: true
          # no parallel flag, just the group name
          group: Recording group v10
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.EXAMPLE_RECORDING_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}