name: example-debug
on:
  push:
    branches:
      - 'master'
  pull_request:
jobs:
  nightly:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress debug logs 📝
        uses: ./
        env:
          DEBUG: '@cypress/github-action'
        with:
          working-directory: examples/v9/basic
