name: example-docker
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  docker-browsers:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
        browser:
          # Available browsers listed on https://github.com/cypress-io/cypress-docker-images#browsers
          - chrome
          - edge
          - firefox
        exclude:
          - os: ubuntu-24.04-arm
            browser: edge # not available for Linux/arm64
    # Cypress Docker image documentation on https://github.com/cypress-io/cypress-docker-images
    container:
      image: cypress/browsers:24.19.0
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Cypress tests
        uses: ./ # if copying, replace with cypress-io/github-action@v7
        with:
          working-directory: examples/basic
          browser: ${{ matrix.browser }}
