name: example-firefox
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  firefox:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Firefox
        uses: ./ # if copying, replace with cypress-io/github-action@v7
        timeout-minutes: 3
        with:
          # let's show browser and system info
          build: npx cypress info
          working-directory: examples/browser
          browser: firefox

      # report screenshot size and store the screenshots as test artifacts
      - uses: actions/upload-artifact@v7
        with:
          name: screenshots-in-firefox-${{ matrix.os }}
          path: examples/browser/cypress/screenshots
