name: example-cron
on:
  schedule:
    # runs tests every day at 4am
    - cron: '0 4 * * *'
  workflow_dispatch:
permissions:
  contents: read

jobs:
  nightly:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Cypress nightly tests 🌃
        uses: ./ # if copying, replace with cypress-io/github-action@v7
        with:
          working-directory: examples/basic
